### ISSUE TITLE
vit_keras

### ISSUE THREAD

**Issue by tjwy** [KatherLab/dl-mri#1]
If I run "from vit import vit_b16" as per your code, I get an error: "ImportError: cannot import name 'vit_b16' from 'vit'". However, when I modify the code to "from vit_keras.vit import vit_b16", I can successfully import the VIT model. But it seems that the contents of the vit_keras folder you provided are not being utilized. What could be the issue here?

**Comment by Xiaofeng-Jiang** [comment]
@tjwy Thank you for pointing this out! If "vit_keras" is installed correctly, you should be able to run "from vit import vit_b16" directly. The "vit_keras" folder is primarily intended for visualization purposes and should not directly affect the import process.

**Comment by tjwy** [comment]
Thank you for your response! In addition to vit_b16 and CNN, have you tried other models that can achieve better results? I am currently looking for a pre-trained image encoder for MRI images, similar to DINOv2 for natural images. Do you have any information on this?

**Comment by Xiaofeng-Jiang** [comment]
> Thank you for your response! In addition to vit_b16 and CNN, have you tried other models that can achieve better results? I am currently looking for a pre-trained image encoder for MRI images, similar to DINOv2 for natural images. Do you have any information on this?

You might find this article useful: https://www.nature.com/articles/s42256-024-00807-9. I will now close this issue.
